name: 'Format Code'

on:
  push:
    branches:
      - main
      - next

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Format
        run: pnpm format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[ci] format'
          branch: ${{ github.head_ref }}
